# Site settings
title: David's Blog
email: David.Moore.TN@gmail.com
url: "http://david-moore.me"
description: "Thoughts of a Knoxville programmer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: David Moore
  location: Knoxville TN

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sorakiu
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/sorakiu
  - title: github
    url: http://github.com/sorakiu

# Postal address (add as many lines as necessary)
address:
  - line: Knoxville, TN

# Credits content
credits: 'Adapted from the Freelancer theme.  Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - portfolio

gems:
  - jekyll-sitemap
