# Site settings
title: David's Blog
email: sorakiu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts of a Knoxville programmer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://david-moore.me" # the base hostname & protocol for your site
twitter_username: sorakiu
github_username:  sorakiu

# Build settings
markdown: kramdown
highlighter: rouge

